### ISSUE TITLE
Issues with Automaton.Intersection

### ISSUE THREAD

**Issue by Fread75** [moodmosaic/Fare#16]
Hello,

Before all, thanks for you portage, this is exactly what I was looking for, unfortunately I encounter an issue with the only method I need.

I have an issue with those 2 following basic tests I made with the Intersection method :
* I defined the 2 RegExp : "ab.\*" and "a.\*", when I try to calculate their intersection I receive an System.OutOfMemoryException
* I defined the 2 RegExp : "ab" and "ab" (they are identical), I calculate their intersection and proceed to call "Reduce" on the resulting automaton, and that makes this automatons empty (and can't recognize "ab" as a valid string)

**Comment by moodmosaic** [comment]
Thank you for reporting this! I'll take a look but I can't promise if I'll be able to fix it :smiley:

**Comment by Fread75** [comment]
Hello,

I just made the same test with the original java package and everything works fine, it seems to be a java to C# conversion issue.

**Comment by moodmosaic** [comment]
Thanks for the hint!

**Comment by moodmosaic** [comment]
Now that #17 has been merged, should we close this? :smiley:

**Comment by Fread75** [comment]
Yeah of course, sorry it was my first time with git and github, I thought
that it would be possible to link an issue with a pull request.
Le 25 févr. 2016 05:33, "Nikos Baxevanis" <notifications@github.com> a
écrit :

**Comment by moodmosaic** [comment]
:+1: That's fine! Thank you for your decent work!
