### ISSUE TITLE
Xeger dont recognize \s as space

### ISSUE THREAD

**Issue by TomerHaber1** [moodmosaic/Fare#20]
When i use "\s" in my regex, Xeger puts an 's' in the result.

**Comment by moodmosaic** [comment]
Thank you for reporting this!

Project Fare turns Regular Expressions into [Automatons](http://en.wikipedia.org/wiki/Deterministic_finite_automaton) by applying the algorithms of [dk.brics.automaton](http://www.brics.dk/automaton/) and [xeger](https://code.google.com/p/xeger/).

Unfortunately, I don't have an answer to your question, as Project Fare is really a port of the above Java projects. – We'd have to try "\s" in Java and compare the results.

You may use a different pattern or use a different *engine* to reverse the Regular Expression into an Automaton. As an example, you can use the [Rex](http://research.microsoft.com/en-us/projects/rex/) engine.
