### ISSUE TITLE
Strong Name Signing

### ISSUE THREAD

**Issue by DanyO** [moodmosaic/Fare#25]
Would it be possible to "Strong Name Sign" the assemblies in this NuGet package?

Referencing/Using this package in a strongly-named assembly results in the following error at runtime:
Could not load file or assembly 'Fare, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by moodmosaic** [comment]
>Would it be possible to "Strong Name Sign" the assemblies in this NuGet package?

Perhaps, it would be possible, but wouldn't it be a breaking change to existing consumers of the .DLL?

**Comment by JimiC** [comment]
@DanyO Clone the repo and build it by signing it with your own key, assuming that the same `dll` is going to be used in all your projects. Then reference the signed `dll` to your project. I know that this is an extra step of maintenance from your side, but this way everyone gets what he wants and no breaking changes are introduced.

**Comment by moodmosaic** [comment]
See https://github.com/AutoFixture/AutoFixture/pull/972#issuecomment-361206258.

A signed version of the assembly will be released as *Fare.Signed* next to the existing NuGet package. So there will be two NuGet packages:

- Fare
- Fare.Signed

I'll close this once the new NuGet package is pushed.
