### ISSUE TITLE
Push tags corresponding to the releases

### ISSUE THREAD

**Issue by zvirja** [moodmosaic/Fare#29]
I'm looking to work on the https://github.com/AutoFixture/AutoFixture/issues/938. I would like to rework the build/versioning system to make it similar to the AutoFixture model (where it's CI based). It's well described [here](https://github.com/AutoFixture/AutoFixture/wiki/Project-processes#release-process).

The first step (and basically for the consistency) I need repo to contain the tags. Could you please add the tags corresponding to the existing releases? Unfortunately, I cannot push them via PR 😕

**Comment by moodmosaic** [comment]
Sure, I can add them, but it might take me a few days before I get to it.

Happy to give you push permissions if you want to do this yourself.

**Comment by zvirja** [comment]
@moodmosaic I'm perfectly fine to wait a few days before the tags are arranged :) Please ensure to prefix them with `v` (i.e. `v1.0.0`) - that's required by the build scripts.

For now I don't want to own this project and will be fine if it's owned by you 😅

**Comment by moodmosaic** [comment]
Having push permissions doesn't mean you own it per se.

I'm make sure to prefix the tags with v.

**Comment by zvirja** [comment]
I know, but due to some reasons had that feeling 😉

Let me know if you need my assistance with this or AppVeyor setup and I'll gladly help 👍

**Comment by moodmosaic** [comment]
@zvirja, I just pushed the tags.

**Comment by moodmosaic** [comment]
So now I think we should close this one?

**Comment by zvirja** [comment]
Yep. It's done.
