### ISSUE TITLE
Xeger throws if regex contains "(#)"

### ISSUE THREAD

**Issue by BenjiDNet** [moodmosaic/Fare#32]
We are using Fare / Xeger to generate Data from a specific Regex, but if the Regex contains "(#)" 
(like in this one: "\\d{8}(#)\\d{3}" ) it throws an InvalidOperationException "State" while generating.

**Comment by moodmosaic** [comment]
Thank you for reporting this!

Project Fare turns Regular Expressions into [Automatons](http://en.wikipedia.org/wiki/Deterministic_finite_automaton) by applying the algorithms of [dk.brics.automaton](http://www.brics.dk/automaton/) and [xeger](https://code.google.com/p/xeger/).

Unfortunately, I don't have an answer to your question, as Project Fare is really a port of the above Java projects. – We'd have to try

```
\d{8}(#)\d{3}
```

in Java and compare the results.

You may use a different pattern or use a different _engine_ to reverse the Regular Expression into an Automaton. As an example, you can use the [Rex](http://research.microsoft.com/en-us/projects/rex/) engine.

**Comment by moodmosaic** [comment]
@BenjiDNet, could you check if https://github.com/moodmosaic/Fare/pull/55 solves your issue? If it does, we can do a release soon.

**Comment by BenjiDNet** [comment]
@moodmosaic we worked around this by catching any Regex with '#', and left it at that. -Therefor this can be closed, thanks for your feedback!

**Comment by moodmosaic** [comment]
Sounds good. Thanks for letting me know.
