### ISSUE TITLE
Invalid licenseUrl in nuget package

### ISSUE THREAD

**Issue by lerppana** [moodmosaic/Fare#40]
Hello!

Did you know that licenseUrl in your nuget package has a typo:
https://github.com/moodmosaic/Fare/blob/master/LICENCE

LICENCE with C

-Lassi

**Comment by moodmosaic** [comment]
Thank you for reporting this 👍 I'll take a look and fix it as soon as possible (currently, I'm travelling, so it might take me a day or two before I do this).

**Comment by moodmosaic** [comment]
(Feel free to open a pull request if you feel like it.)

**Comment by moodmosaic** [comment]
@zvirja, do you know where we put the license URL after #30?

**Comment by moodmosaic** [comment]
This has been fixed on `master` via #41 (notice the typo in the PR title and git commit message, well that's the tax I have to pay for doing git stuff on a plane).

Thanks for all the help 👍 🚀

**Comment by moodmosaic** [comment]
I just pushed https://www.nuget.org/packages/Fare/2.1.2 which fixes that license typo.
