### ISSUE TITLE
locks up generating a value

### ISSUE THREAD

**Issue by sprotty** [moodmosaic/Fare#45]
string patternPropertyName = (new Fare.Xeger("(.*)docker_builder")).Generate();

Would maybe be worth adding some kind of timeout or limit to the generate function so issues like this don't kill an application.

**Comment by moodmosaic** [comment]
Couldn’t you use https://github.com/App-vNext/Polly for dealing with retries and timeouts?

**Comment by moodmosaic** [comment]
We could add a `Generate` overload that takes some kind of *options* where you can specify a timeout, but this would internally consume a library like https://github.com/App-vNext/Polly.

Usually, you'd want to use Polly in the context of a [cross-cutting concern](https://en.wikipedia.org/wiki/Cross-cutting_concern), which better fits in the *application* space rather having it embedded in individual libraries.

---

Close this. Feel free to re-open this, or add comments to it, however.
