### ISSUE TITLE
NuGet.org License link points to https://github.com/moodmosaic/Fare/blob/master/LICENCE

### ISSUE THREAD

**Issue by CeesKaas** [moodmosaic/Fare#46]
the link to the license on nuget.org points to https://github.com/moodmosaic/Fare/blob/master/LICENCE instead of https://github.com/moodmosaic/Fare/blob/master/LICENSE

**Comment by moodmosaic** [comment]
I thought we fixed that in https://github.com/moodmosaic/Fare/pull/41.

**Comment by moodmosaic** [comment]
So, it *is* actually fixed in the source code... We just need to release a new version on NuGet Gallery. Thanks for the heads up. This should be automatically resolved in the next release. :+1:

**Comment by CeesKaas** [comment]
sorry forgot to check already closed issues

**Comment by moodmosaic** [comment]
No problem :+1:

**Comment by moodmosaic** [comment]
I just pushed https://www.nuget.org/packages/Fare/2.1.2 which fixes that license typo.
