### ISSUE TITLE
Xeger sometimes fails to generate a string matching this regex: @"^[^\s]+$"

### ISSUE THREAD

**Issue by nasskov** [moodmosaic/Fare#47]
The RegEx pattern: @"^[^\s]+$" expects a string without spaces, yet Xeger sometimes generates results which are contradicting this requirement.
A code to prove it:
```
public void XegerIssueProof()
{
    string pattern = @"^[^\s]+$";
    for (int i = 0; i < 50000; i++)
    {
        string result = new Xeger(pattern).Generate();
        if (!Regex.IsMatch(result, pattern))
        {
            throw new Exception($"Failed at attempt:{i}, generated string is: '{result}'");
        }
    }
}
```

Some results:
Failed at attempt:9150, generated string is: ' ~v'
Failed at attempt:1, generated string is: ' {uyz{_z'
Failed at attempt:3397, generated string is: 'a t|o'

**Comment by moodmosaic** [comment]
Thank you for reporting this!

Project Fare turns Regular Expressions into [Automatons](http://en.wikipedia.org/wiki/Deterministic_finite_automaton) by applying the algorithms of [dk.brics.automaton](http://www.brics.dk/automaton/) and [xeger](https://code.google.com/p/xeger/).

Unfortunately, I don't have an answer to your question, as Project Fare is really a port of the above Java projects.

You may use a different pattern or use a different _engine_ to reverse the Regular Expression into an Automaton. As an example, you can use the [Rex](http://research.microsoft.com/en-us/projects/rex/) engine.

You are more than welcome to troubleshoot/debug this and open a pull request :heart: Until then, I'm going to close this. Feel free to reopen it or add comments to it.
