### ISSUE TITLE
support .net framework v4.8

### ISSUE THREAD

**Issue by tedyyu** [moodmosaic/Fare#61]
Hi, 

Can you help to add the support of .net framework v4.8?
It's supported only up to v3.5, based on https://www.nuget.org/packages/Fare/.
Thanks for the attention.

Best regards,
Tedy

**Comment by moodmosaic** [comment]
@tedyyu, have you tried referencing the NuGet Package? It should be compatible with .NET Framework 3.5 and higher, and also with .NET Standard 1.1 and higher:

https://github.com/moodmosaic/Fare/blob/bc457f463158ce8fa1918313a3314b8b6af1ef20/Src/Fare/Fare.csproj#L5

Let me know what errors you get.

**Comment by tedyyu** [comment]
My peer says it works by using NuGet one in our v4.8 project. So no problem, thanks.
