### ISSUE TITLE
License url invalid

### ISSUE THREAD

**Issue by U52284** [moodmosaic/Fare#63]
The url to the license should be [https://raw.githubusercontent.com/moodmosaic/Fare/master/LICENSE](https://raw.githubusercontent.com/moodmosaic/Fare/master/LICENSE) instead.

**Comment by moodmosaic** [comment]
Thank you! You mean in the NuGet package, right?

**Comment by moodmosaic** [comment]
If it's possible to edit the metadata, it'll make the update faster. (If not, we'll have to publish a new release.)

**Comment by U52284** [comment]
I have seen that there is a project url as well as a Repository url. I need to investigate the tooling i use.
